language:
  ruby
rvm:
  2.6.3
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE bbpt;'
install: 
  - gem install rails
  - bundle install
script:
  - brakeman
  - rails db:migrate
  - rails t