language:
  ruby
rvm:
  2.6.3
services:
  - mysql
env:
  - BLAZINGKINPARTYPACK_DATABASE_USERNAME=root
before_install:
  - mysql -e 'CREATE DATABASE bppt;'
install: 
  - gem install rails
  - bundle install
script:
  - brakeman
  - rails db:migrate
  - rails t