language:
  ruby
rvm:
  2.6.3
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE `blazingkin-party-pack_test`;'
install: 
  - gem install rails
  - bundle install
script:
  - brakeman
  - rails db:migrate
  - rails t